;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	forward-sexp
	indent-for-tab-command
	kill-current-buffer
	kill-region
	kill-sexp
	mc/mark-next-lines
	paredit-backward
	paredit-forward
	scroll-right
	sgml-skip-tag-forward
	))

(setq mc/cmds-to-run-once
      '(
	ace-window
	beginning-of-buffer
	describe-key-briefly
	helm-M-x
	scroll-left
	sgml-skip-tag-backward
	yas-expand
	))
