(find-file "/home/winston/main.org")
(add-hook 'after-init-hook '(lambda ()
			      (load "/home/winston/.emacs.d/themes/euphoria-theme.el")
			      (load "/home/winston/.emacs.d/noexternals.el")
			      (load "/home/winston/.emacs.d/loadpackages.el")))
