(local-set-key (kbd "C-c a") 'org-agenda)
(local-set-key (kbd "C-M-f") 'org-forward-heading-same-level)
(local-set-key (kbd "C-M-b") 'org-backward-heading-same-level)
(local-set-key (kbd "C-c C-f") 'org-down-element)
(local-set-key (kbd "C-c C-b") 'org-up-element)
